# Generated by Django 3.2.6 on 2022-12-22 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Labels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Lables',
                'verbose_name_plural': 'Lables',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Desc', models.TextField(default='')),
                ('Img', models.ImageField(upload_to='')),
                ('Company', models.CharField(max_length=150)),
                ('Stock', models.CharField(max_length=10)),
                ('Created', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('Price', models.CharField(max_length=10)),
                ('Type', models.CharField(default='New', max_length=10)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Product',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qty', models.CharField(max_length=10)),
                ('Prod_Id', models.ManyToManyField(to='Eco_Store.Product')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Cart',
            },
        ),
    ]
