# Generated by Django 3.2.6 on 2022-12-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eco_Store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Leafs',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
